### ISSUE TITLE
Allow instantiated models to be added to a store.

### ISSUE THREAD

**Issue by JasperStam** [CodeYellowBV/mobx-spine#18]
Currently the store only supports model data, objects, to be added.

**Comment by SpaceK33z** [comment]
Dupe of #12

**Comment by JasperStam** [comment]
No it's not, in the store.add this happens:
```
 @action add(models) {
        const singular = !isArray(models);
        models = singular ? [models] : models.slice();

        const modelInstances = models.map(this._newModel.bind(this));
```

_newModel is always called, it isn't checked if the given models are instantiated or just objects

**Comment by SpaceK33z** [comment]
Re-opening since @abzainuddin also requested this feature. It has a lot to do with #12, but can be seen as a separate feature.

**Comment by SpaceK33z** [comment]
Interesting point brought up by Burhan, what do we do with the `store` of a model?

**Comment by SpaceK33z** [comment]
This isn't a feature that is necessary very often; if you need it I recommend to use `store.models.push(model)`. This essentially bypasses mobx-spine a bit, but since adding instantiated models to a store can cause all sorts of problems I think this is fine.
