### ISSUE TITLE
Saving relations but not saving related model

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/mobx-spine#27]
I'm trying to create a new Order with a related Customer, so:

```
const order = new Order({ id }, { relations: ['customer'] });
order.customer = existingCustomer
order.saveAll()
```

The request then becomes something like:

```
{
    "data": [
        {
            "id": -11,
            "customer": 2,
        }
    ],
    "with": {
        "customer": [
            {
                "id": 2,
                "name": "zjoef"
            }
        ],
    }
}
```
The customer is also saved (`with.customer`), but actually I don't want that. I just want to set the customer id of the order, and not save the customer. Setting `order.customer.id = 2` doesn't help because the `with.customer.name` is then an empty string. So I try something like this:

```
const order = new Order({ id });
order.customer = existingCustomer.id
order.saveAll()
```

But now the customer is not POSTed to the backend, since it is not defined as an attribute on Order.

How can I set the related customer id without actually saving the customer?

**Comment by SpaceK33z** [comment]
There are a couple of options here;

- For this specific thing you don't seem to need `.saveAll()`, `.save()` would suffice, right? That would maybe already fix your issue for now.
- you can override `toBackendAll()` on the model, something like this:

```js
toBackendAll() {
  const data = super.toBackendAll();

  data.relations.customer = undefined;
}
```

- I can make an option for `saveAll()` which, when it's given, will only include the mentioned relations. `saveAll({ relations: [] })`?

**Comment by abzainuddin** [comment]
Alas I need to save more in 1 go, so I guess I'm stuck with `saveAll`.

Saving like this happens quite often, for this example an order has a `Customer`, `Equipment` and a `Driver`, so adding an option to `saveAll` would be best?
