### ISSUE TITLE
Saving related store

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/mobx-spine#28]
I want to save a `Ride` which has `Activities`:

```
const ride = new Ride({}, { relations: ['activities'] });
ride.activities.add({ ride });
ride.activities.add({ ride });
ride.activities.add({ ride });
ride.saveAll()
```

The request becomes something like this:

```
{
    "data": [
        {
            "id": -98,
        }
    ],
    "with": {
        "ride": [
            {
                "id": -104
            },
            {
                "id": -105
            },
            {
                "id": -106
            }
        ],
        "activity": [
            {
                "id": -101,
                "ride": -104
            },
            {
                "id": -102,
                "ride": -105
            },
            {
                "id": -103,
                "ride": -106
            }
        ]
    }
}
```
It doesn't relate the activities with the single ride, but creates a ride per activity.

**Comment by SpaceK33z** [comment]
Why are you adding `{ ride }` with each activity? The ride you create at the top is already the parent relation, so it seems unnecessary to add it as child relation too?

**Comment by abzainuddin** [comment]
That's true! If I don't add the ride to each activity, then the request is "incomplete":

```
(handcoded)
{
  data: {
    id: -1,
    activities: [-2]
  },
  with: {
    activity: [{
      id: -2,
      // ride: -1, <--- missing
    }]
  }
}
```
So binder expects both models to set the relations properly. Tried to set the ride manually hoping that mobx-spine would recognize it's the same instance.

**Comment by SpaceK33z** [comment]
Discussed with Marcel and this is a Binder issue, https://github.com/CodeYellowBV/django-binder/issues/57.
