### ISSUE TITLE
Add store sorting

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/mobx-spine#30]
How should I keep a Store stored? Currently I modify the `.models` directly, but built-in support is nice.

You might argue that sorting is a view specific thing, and that the order in the Store shouldn't matter...but it's damn handy that you can keep a Store sorted.

For example, I have a list of activities which can be sorted. I'm using a package which has a nice `arrayMove` function to move from `oldIndex` to `newIndex`. If you sort in the view, then those indexes don't match with your store indexes. Fixable, but annoying.

**Comment by SpaceK33z** [comment]
I can implement this the same way as Backbone does.
So you have a `comparator` option on the store which can be a function or a string. Perhaps a method to update the `comparator`? And finally a `sort()` method on the store to force a re-sort (which you would almost never need to do manually).

**Comment by SpaceK33z** [comment]
Fixed in 519dbc3596cbcd2e80eb945a8b30e21be31fdb58
