### ISSUE TITLE
Attribute url breaks url()

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/mobx-spine#33]
When you define a `url` attribute, the `url()` function breaks (`fetch`, `save` etc too).

**Comment by SpaceK33z** [comment]
... what did you expect ;p

**Comment by SpaceK33z** [comment]
I can show a clear error when you try to do this, but I can't really make a `url` attribute work without a major overhaul.

**Comment by SpaceK33z** [comment]
Discussed with @abzainuddin, I'll make it a clear e rror.
