### ISSUE TITLE
Model defaults aren't Casted

### ISSUE THREAD

**Issue by JasperStam** [CodeYellowBV/mobx-spine#57]
We have a model with duration values:

```js
export class Driver extends Model {
    static backendResourceName = 'driver';

    @observable id = null;
    @observable remainingTime = 0;

    casts() {
        return {
            remainingTime: Casts.durationMinutes,
        };
    }
}
```

The durationMinutes cast looks like this:
```js
export const Casts = {
    ...BCasts,
    durationMinutes: {
        parse(attr, value) {
            if (value === null) {
                return null;
            }
            return moment.duration(value, 'minutes');
        },
        toJS(attr, value) {
            if (value === null) {
                return null;
            }
            return value.asMinutes();
        },
    },
};
```

However, when we create a `new Driver()` in the frontend, the default `0` isn't casted (durationMinutes.parse isn't called on `0`). This crashes the frontend as it tried to do `0.asMinutes()`

I expect model defaults to also be casted.

**Comment by SpaceK33z** [comment]
This was actually by design. The model defaults should be parsed already, because they directly represent the value of the attribute. In the sense that, `model.remainingTime` directly refers to `@observable remainingTime`. 

Furthermore I like the current behavior because it easily allows you to play with dates, e.g. `@observable dateOfBirth = moment().subtract(18,'years')`

**Comment by JasperStam** [comment]
Ah if that works this issue can be closed.
In python I tend to avoid defining instances (like `{}` or `[]`) in class defaults as they are then shared between instances, which results in really weird behavior.

**Comment by SpaceK33z** [comment]
ah yes that's tricky in Python. In JS this is the same:

```js
class Animal {
  @observable date = moment();
}
```

```js
class Animal {
  constructor() {
    this.date = moment();
  }
}
```
