### ISSUE TITLE
Django-binder and mobx-spine double foreign key issue

### ISSUE THREAD

**Issue by riccardo92** [CodeYellowBV/mobx-spine#62]
When I have two foreign keys in a model, pointing to the same (but another) model, they will not be seen as relations in mobx spine. Let me explain, I have the following foreign keys in the model **Trip**:

```
	start_location = models.ForeignKey('base.Location', 
									on_delete=models.PROTECT, 
									related_name='start_trips',
									null=True,
									blank=True)
	end_location = models.ForeignKey('base.Location', 
									on_delete=models.PROTECT, 
									related_name='end_trips',
									null=True,
									blank=True)
```

In the frontend, I specify the relation as:
```
relations() {
        return {
            ...,
            start_location: Location,
            end_location: Location,
            ...
        };
}
```

and retrieve the Trip and location relations using:

```
        this.trip = new Trip(
            { id: id ? parseInt(id) : null },
            {
                relations: [
                    ...,
                    'start_location',
                    'end_location',
                    ...
                ],
            }
        );
```

The Trip object will not contain any start_location or end_location after calling .fetch().

If in Django, I only use one location and give it related name "trips", it does work. How to have two foreign keys?

**Comment by SpaceK33z** [comment]
The frontend camelCases all relations and attributes, so e.g `start_location` should be `startLocation`;

```
relations() {
        return {
            ...,
            startLocation: Location,
            endLocation: Location,
            ...
        };
}
```

This was done because camelCasing in JavaScript is used everywhere, so we had to choose between some magic by camelCasing all fields OR having unexpected snake_cased fields everywhere.

**Comment by riccardo92** [comment]
Thanks a million, this saved me some headaches.
